FROM golang:1.26.4-bookworm

RUN apt-get update && \
  apt-get install -y sqlite3 libsqlite3-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@v1.61.1

ENV APP_AUTH="/app/secrets" \
  SERVER_BIND_TO="0.0.0.0:8001"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8001

CMD ["air", "-c", ".air.toml"]
